ALTER TABLE items DROP COLUMN tax;

ALTER TABLE items ADD COLUMN brand CHARACTER VARYING;

ALTER TABLE items DROP COLUMN manufactureCode;
ALTER TABLE items DROP COLUMN numenclType;

ALTER TABLE items DROP COLUMN price;
ALTER TABLE items ADD COLUMN inPrice CHARACTER VARYING;
ALTER TABLE items ADD COLUMN tradePrice CHARACTER VARYING;
ALTER TABLE items ADD COLUMN retailPrice CHARACTER VARYING;
