ALTER TABLE companies ADD COLUMN lastbillnumber CHARACTER VARYING;
ALTER TABLE companies ADD COLUMN lastactnumber CHARACTER VARYING;
ALTER TABLE companies ADD COLUMN lasttorg12number CHARACTER VARYING;