ALTER TABLE clients ADD COLUMN numberBill CHARACTER VARYING;
ALTER TABLE clients ADD COLUMN currency CHARACTER VARYING;
ALTER TABLE clients ADD COLUMN bik CHARACTER VARYING;
ALTER TABLE clients ADD COLUMN korrBill CHARACTER VARYING;
ALTER TABLE clients ADD COLUMN bank CHARACTER VARYING;

ALTER TABLE suppliers ADD COLUMN numberBill CHARACTER VARYING;
ALTER TABLE suppliers ADD COLUMN currency CHARACTER VARYING;
ALTER TABLE suppliers ADD COLUMN bik CHARACTER VARYING;
ALTER TABLE suppliers ADD COLUMN korrBill CHARACTER VARYING;
ALTER TABLE suppliers ADD COLUMN bank CHARACTER VARYING;