ALTER TABLE companies ADD COLUMN bill CHARACTER VARYING;
ALTER TABLE companies ADD COLUMN kbill CHARACTER VARYING;
ALTER TABLE companies ADD COLUMN bik CHARACTER VARYING;
ALTER TABLE companies ADD COLUMN bank CHARACTER VARYING;
-- ALTER TABLE companies ADD COLUMN bik CHARACTER VARYING;
